import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/navbar/Navbar";
import '@/Components/Responsive.css';
import '@/app/navbar.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        
        {children}
        
        
        </body>
    </html>
  );
}
